using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Memberships.Entities
{
    [Table("Section")] // Specify table name
    public class Section
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Autogenerated nr
        public int Id { get; set; }

        [MaxLength(255)] // Max chars
        [Required] // Requiered field
        public string Title { get; set; }
    }
}